spid_oidc_rp/urls.py
from django.urls import path

from . views import (oidc_rpinitiated_logout,
                     AgidOidcRpBeginView,
                     AgidOidcRpCallbackEchoAttributes,
                     AgidOidcRpCallbackView)

app_name = "spid_oidc_rp"
urlpatterns = []
urlpatterns += path('oidc/rp/begin',
                    AgidOidcRpBeginView.as_view(),
                    name='spid_oidc_rp_begin'),
urlpatterns += path('oidc/rp/callback',
                    AgidOidcRpCallbackView.as_view(),
                    name='spid_oidc_rp_callback'),
urlpatterns += path('echo_attributes',
                    AgidOidcRpCallbackEchoAttributes.as_view(),
                    name='spid_oidc_rp_echo_attributes'),

urlpatterns += path('oidc/rpinitiated_logout',
                    oidc_rpinitiated_logout,
                    name='spid_oidc_rpinitiated_logout'),

spid_oidc_rp/templates/echo_attributes.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  </head>
  <body>
    <h1>OIDC attributes</h1>
    <dl>
      {% for attribute, value in oidc_rp_user_attrs.items %}
      <dt>{{ attribute }}:</dt>
      <dd>{{ value }}</dd>
      {% endfor %}
    </dl>

    <p><a href="{% url 'spid_oidc_rp:spid_oidc_rpinitiated_logout' %}">Log out</a></p>
  </body>
</html>